### ISSUE TITLE
Creación de la Base de Datos

### ISSUE THREAD

**Issue by germfema** [UAX-2-DAM-Acceso-a-Datos/AppFutbol-Api#3]
Idea inicial:

Tabla jugadores
- Id
- Nombre completa
- Edad
- Nacionalidad
- urlFoto
- **Id de su equipo**

Tabla equipos
- Id
- Nombre
- Liga
- País
- urlFoto
- **Id de su estadio**

Tabla estadios
- Id
- Nombre
- Ciudad
- Capacidad
- urlFoto
- **Id del equipo que juega**

Tabla entrenadores
- Id 
- Nombre
- Edad
- Nacionalidad
- urlFoto
- **Id de su equipo**

**Las columnas que tendrían que ser claves foráneas (marcado en negrita), crear las columnas pero no relacionarlas como FK, ya que si añadimos un estadio como favorito, tendríamos que añadir también el equipo**

En esas tablas se almacenarán los equipos/entrenadores/estadios/jugadores que sean marcados en la aplicación como favoritos.

Por lo general esta bien, comentad por aquí si queréis cualquier cosa.

**Comment by Medra235** [comment]
[apiFootball.zip](https://github.com/UAX-2-DAM-Acceso-a-Datos/AppFutbol-Api/files/10707479/apiFootball.zip)
